### ISSUE TITLE
Precompiled release?

### ISSUE THREAD

**Issue by htv04** [jamesathey/FreeDiskSysROM#2]
Can you add a precompiled version of the BIOS? I would really like to test this out and see how it fares against the original BIOS. Thanks!

**Comment by htv04** [comment]
So I was able to compile a build, but it isn't working with Mesen. Is this intended for FCEUX?

**Comment by jamesathey** [comment]
Thrilled to see some interest! Unfortunately, if you look at the Status chart in the README.md, you'll see that several critical functions are not implemented yet, including all of the disk I/O and the startup routine.

Once it's finished, it should be a drop-in replacement on any emulator, but it's not there yet.

**Comment by htv04** [comment]
I see. Is there any way to test what's implemented? Either way, good luck with this project, I can't wait to see the final build! I'll try to do whatever I can to help.
